version: "3.9"
services:
    postgresdocker:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        ports:
            - 5433:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 8089:8080
    loginserver:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./components:/loginServer/components
            - ./pages:/loginServer/pages
            - ./public:/loginServer/public
            - ./styles:/loginServer/styles
            - ./.next:/loginServer/.next
            - ./.env:/loginServer/.env
            - ./prisma:/loginServer/prisma
            - ./tailwind.config.js:/loginServer/tailwind.config.js
            - ./postcss.config.js:/loginServer/postcss.config.js
            - ./next.config.js:/loginServer/next.config.js
            - ./next-env.d.ts:/loginServer/next-env.d.ts
            - ./functions:/loginServer/functions
        command: npm run dev
volumes:
    postgres-data:
        driver: local
