version: "3.9"
services:
    authdb:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        # expose:
        #     - "5433"
        ports:
            - 5433:5432
        volumes:
            - loginDBVolume:/var/lib/postgresql/data
    loginserver:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3001:3001
        volumes:
            - ./components:/loginServer/components
            - ./pages:/loginServer/pages
            - ./public:/loginServer/public
            - ./styles:/loginServer/styles
            - ./.next:/loginServer/.next
            - ./.env:/loginServer/.env
            - ./prisma:/loginServer/prisma
            - ./tailwind.config.js:/loginServer/tailwind.config.js
            - ./postcss.config.js:/loginServer/postcss.config.js
            - ./next.config.js:/loginServer/next.config.js
            - ./next-env.d.ts:/loginServer/next-env.d.ts
            - ./functions:/loginServer/functions
        command: bash -c 'npx prisma migrate deploy && npm run dev'
volumes:
    loginDBVolume:
        external: true
networks:
    default:
        external:
            name: gstreet
