version: "3.9"
services:
    authdb:
        env_file:
            - prod.env
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        expose:
            - "5432"
        ports:
            - 5433:5432
        volumes:
            - loginDBVolume:/var/lib/postgresql/data
    loginserver:
        env_file:
            - prod.env
        image: ghcr.io/glennstreetman/login
        ports:
            - 3001:3001
        command: "npm run start"
volumes:
    loginDBVolume:
        external: true
networks:
    default:
        external:
            name: gstreet
