version: "3.9"
services:
    authdb:
        env_file:
            - dev.env
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        ports:
            - 5433:5432
        volumes:
            - loginDBVolume:/var/lib/postgresql/data
    loginserver:
        env_file:
            - dev.env
        user: node
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - .:/loginServer
        command: "bash -c 'npx prisma generate && npm run dev --reload'"
        # command: bash -c 'npx prisma migrate deploy && npm run dev'
volumes:
    loginDBVolume:
        external: true
networks:
    default:
        external:
            name: gstreet
